
use_frameworks!

target 'ImageMetalling-16' do
    platform :osx, '10.13'
    pod 'SnapKit'
    pod 'Surge', :git => 'https://github.com/dnevera/Surge.git', :tag => '1.0.2'
    pod 'IMProcessing', :git => 'https://bitbucket.org/degrader/improcessing', :tag => '0.10.0'
    pod 'IMProcessingUI', :git => 'https://bitbucket.org/degrader/improcessingui', :tag => '0.10.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

