platform :ios, '8.0'


pod 'DegradrMath', :git => 'https://bitbucket.org/degrader/degradr-math.git', :tag => '0.2.0'
pod 'DegradrCore3', :git => 'https://bitbucket.org/degrader/degradr-core-3.git', :tag => '0.6.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
