# Uncomment this line to define a global platform for your project

platform :osx, '10.11'

# Uncomment this line if you're using Swift

use_frameworks!

target 'ImageMetalling-07' do
    pod 'IMProcessing', :path => '../../degradr/IMProcessing'
    #pod 'IMProcessing', :git => 'https://github.com/dnevera/IMProcessing.git'
end

