
use_frameworks!

target 'ImageMetalling-08' do
    platform :osx, '10.11'
    pod 'SnapKit'
    pod 'IMProcessing', :git => 'https://bitbucket.org/degrader/improcessing.git', :tag => '0.5.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
