platform :ios, '8.0'

pod 'DegradrMath', :git => 'https://bitbucket.org/degrader/degradr-math.git'
pod 'DegradrCore3', :git => 'https://bitbucket.org/degrader/degradr-core-3.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
