
use_frameworks!

target 'ImageMetalling-12' do
    platform :osx, '10.11'
    pod 'SnapKit'
    pod 'KFToolbar', :git => 'https://github.com/dnevera/KFToolbar'
    pod 'IMProcessing', :path => '../../degradr/IMProcessing'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

